//Code Generated by Jenga.NET
using Kimtoo.BindingProvider;
using ServiceStack.OrmLite;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Windows.Forms;

namespace Payroll_Management_System.Pages
{
    public partial class Page_Employee : UserControl
    {
        public bool AllowAdd { get; set; } = true;
        public bool AllowDelete { get; set; } = true;
        public bool AllowEdit { get; set; } = true;
        public bool AllowSearch { get; set; } = true;
        public int DataLimit { get; set; } = 0;
        public Func<Payroll_Management_System.Models.Employee, bool> BeforeDelete { get; set; } = null;
        public Dictionary<string, object> FixedValues = new Dictionary<string, object>();
        public Dictionary<string, Action<Payroll_Management_System.Models.Employee>> CustomContextMenu = new Dictionary<string, Action<Payroll_Management_System.Models.Employee>>();
        private Func<Payroll_Management_System.Models.Employee, bool> _dataFilter = null;

        public delegate void JengaEventHandler(Payroll_Management_System.Models.Employee e);

        public event JengaEventHandler SelectionChanged = null;

        public Page_Employee()
        {
            InitializeComponent();
        }

        private static bool IsInDesignMode()
        => (Application.ExecutablePath.IndexOf("devenv.exe", StringComparison.OrdinalIgnoreCase) > -1);

        public void LoadData()
        {
            Cursor.Current = Cursors.WaitCursor;
            //load Custom ContextMenu
            if (contextMenuStrip.Items.Count == 0)
                foreach (var menu in this.CustomContextMenu)
                    contextMenuStrip.Items.Add(menu.Key, null, (s, ee) => menu.Value.Invoke(grid.GetRecord<Payroll_Management_System.Models.Employee>()));

            var data = Kt.Db.Select<Payroll_Management_System.Models.Employee>();
            //-filter EmploymentStatus
            if (cmbFilterEmploymentStatus.SelectedIndex > 0)
                data = data.Where(r => r.EmploymentStatus == cmbFilterEmploymentStatus.SelectedItem.ToString()).ToList();
            //-filter Department
            if (cmbFilterDepartmentID.SelectedItem != null && cmbFilterDepartmentID.SelectedItem.GetType() != typeof(string))
                data = data.Where(r => r.DepartmentID == ((Payroll_Management_System.Models.Department)cmbFilterDepartmentID.SelectedItem).DepartmentID).ToList();
            //filter
            if (_dataFilter != null)
                data = data.Where(r => _dataFilter.Invoke(r)).ToList();

            if (DataLimit > 0)
                data = data.Take(DataLimit).ToList();
            grid.Bind(data);
            Cursor.Current = Cursors.Default;
        }

        private void grid_SelectionChanged(object sender, EventArgs e)
        {
            SelectionChanged?.Invoke(grid.GetRecord<Payroll_Management_System.Models.Employee>());
        }

        public Payroll_Management_System.Models.Employee GetSelectedRecord()
        {
            return grid.GetRecord<Payroll_Management_System.Models.Employee>();
        }

        public IEnumerable<Payroll_Management_System.Models.Employee> GetCurrentRecords()
        {
            return grid.GetRecords<Payroll_Management_System.Models.Employee>();
        }

        public void SetDataFilter(Func<Payroll_Management_System.Models.Employee, bool> predicate)
        {
            _dataFilter = predicate;
            LoadData();
        }

        public void ClearDataFilter()
        {
            _dataFilter = null;
            LoadData();
        }

        private void LoadFilters()
        {
            Cursor.Current = Cursors.WaitCursor;
            txtSearch.Text = "";
            var db = Kt.Db;
            //Fetch data for Department  dropdown filter (cmbFilterDepartmentID)
            cmbFilterDepartmentID.Items.Clear();
            var cmbDepartmentIDData = db.Select<Payroll_Management_System.Models.Department>();
            cmbFilterDepartmentID.Items.Add("Department (All)");
            cmbFilterDepartmentID.Items.AddRange(cmbDepartmentIDData.ToArray());
            cmbFilterDepartmentID.SelectedIndex = 0;
            //fetch-filter
            Cursor.Current = Cursors.Default;
        }

        private void Page_Employee_Load(object sender, EventArgs e)
        {
            ColEdit.Visible = this.AllowEdit;
            btnAdd.Visible = this.AllowAdd;
            txtSearch.Visible = btnSearch.Visible = this.AllowSearch;
            grid.AllowUserToDeleteRows = colDel.Visible = btnDelete.Visible = this.AllowDelete;
            //disable rendering on design time
            if (IsInDesignMode()) return;
            LoadFilters();

            //-Add code for deletion using Binding Provider
            if (this.AllowDelete)
                grid.OnDelete<Payroll_Management_System.Models.Employee>((r, i) => Kt.Db.Delete(r) > 0);
            //init
            LoadData();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            var frm = new Payroll_Management_System.Forms.Frm_Employee();
            frm.FixedValues = this.FixedValues;
            frm.ShowDialog();
            LoadData();
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (BeforeDelete != null)
                    if (!BeforeDelete.Invoke(GetSelectedRecord()))
                        return;
                grid.DeleteRow<Payroll_Management_System.Models.Employee>();
            }
            catch (Exception)
            {
            }
        }

        private void txtSearch_KeyUp(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                if (txtSearch.Text.Trim().Length > 0)
                    grid.SearchRows(txtSearch.Text);
                else
                    LoadData();
            }
        }

        private void btnSearch_Click(object sender, EventArgs e)
        {
            if (txtSearch.Text.Trim().Length > 0)
                grid.SearchRows(txtSearch.Text);
            else
                LoadData();
        }

        private void filters_SelectionChangeCommitted(object sender, EventArgs e)
        {
            txtSearch.Reset();
            LoadData();
        }

        private void grid_CellContentDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.ColumnIndex == lnkDepartmentID.Index)
            {
                var db = Kt.Db;
                new Payroll_Management_System.Forms.Frm_Department(db.SingleById<Payroll_Management_System.Models.Department>(grid.GetRecord<Payroll_Management_System.Models.Employee>().DepartmentID), true).ShowDialog();
            }
            //frmLink
        }

        private void btnReload_Click(object sender, EventArgs e)
        {
            LoadFilters();
            LoadData();
        }

        private void contextMenuStrip_Opening(object sender, CancelEventArgs e)
        => e.Cancel = !(grid.SelectedRows.Count > 0 && CustomContextMenu.Count() > 0);

        private void grid_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.ColumnIndex == ColEdit.Index)
            {
                var frm = new Payroll_Management_System.Forms.Frm_Employee(grid.GetRecord<Payroll_Management_System.Models.Employee>());
                frm.FixedValues = this.FixedValues;
                frm.ShowDialog();
                LoadData();
            }

            if (e.ColumnIndex == colDel.Index)
                grid.DeleteRow<Payroll_Management_System.Models.Employee>();
        }
    }
}