//Code Generated by Jenga.NET
			namespace Payroll_Management_System.Pages
			{
			partial class Page_Employee
			{

			private System.ComponentModel.IContainer components = null;

			protected override void Dispose(bool disposing)
			{
			if (disposing && (components != null))
			{
			components.Dispose();
			}
			base.Dispose(disposing);
			}

			#region Component Designer generated code

			private void InitializeComponent()
			{
			 this.components = new System.ComponentModel.Container();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
		    System.Windows.Forms.DataGridViewCellStyle colProgressStyle = new System.Windows.Forms.DataGridViewCellStyle(); 
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			this.grid = new Bunifu.UI.WinForms.BunifuDataGridView();
			this.colAvatar = new System.Windows.Forms.DataGridViewImageColumn();
			this.ColEdit = new System.Windows.Forms.DataGridViewLinkColumn();
			this.colDel = new System.Windows.Forms.DataGridViewLinkColumn();
			this.txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
			this.btnDelete = new System.Windows.Forms.Button();
			this.btnAdd = new System.Windows.Forms.Button();
			this.pnlActions = new System.Windows.Forms.Panel();
			this.btnSearch = new System.Windows.Forms.Button();
			this.btnReload = new System.Windows.Forms.Button();
			 this.contextMenuStrip = new System.Windows.Forms.ContextMenuStrip(this.components);
			((System.ComponentModel.ISupportInitialize)(this.grid)).BeginInit();
			this.pnlActions.SuspendLayout();
			this.lnkFullName = new System.Windows.Forms.DataGridViewTextBoxColumn();
this.lnkGender = new System.Windows.Forms.DataGridViewTextBoxColumn();
this.lnkJoinDate = new System.Windows.Forms.DataGridViewTextBoxColumn();
this.cmbFilterEmploymentStatus = new Bunifu.UI.WinForms.BunifuDropdown();this.lnkEmploymentStatus = new System.Windows.Forms.DataGridViewImageColumn();
this.cmbFilterDepartmentID = new Bunifu.UI.WinForms.BunifuDropdown();this.lnkDepartmentID = new System.Windows.Forms.DataGridViewImageColumn();
this.lnkDesignation = new System.Windows.Forms.DataGridViewTextBoxColumn();
this.lnkOnLeave = new System.Windows.Forms.DataGridViewTextBoxColumn();
this.lnkBasicSalary = new System.Windows.Forms.DataGridViewTextBoxColumn();
this.lnkGetAllowances8 = new System.Windows.Forms.DataGridViewTextBoxColumn();
this.lnkGetDeductions9 = new System.Windows.Forms.DataGridViewTextBoxColumn();
this.lnkGetGrossPay10 = new System.Windows.Forms.DataGridViewTextBoxColumn();
this.lnkGetNetPay11 = new System.Windows.Forms.DataGridViewTextBoxColumn();
//init
			this.SuspendLayout();

			//
			// colProgressStyle
			// 
            colProgressStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 6.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            colProgressStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			//
			// grid
			//
			this.grid.AllowCustomTheming = true;
			this.grid.AllowUserToAddRows = false;
		    this.grid.AllowUserToResizeRows = false;
			this.grid.MultiSelect = false;
			this.grid.ReadOnly=true;
			this.grid.ContextMenuStrip = this.contextMenuStrip;
			dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
			dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
			this.grid.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
			this.grid.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
			| System.Windows.Forms.AnchorStyles.Left)
			| System.Windows.Forms.AnchorStyles.Right)));
			this.grid.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.grid.BackgroundColor = System.Drawing.SystemColors.Control;
			this.grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
			this.grid.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
			this.grid.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
			dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
			dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
			dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
			dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
			dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.grid.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			this.grid.ColumnHeadersHeight = 40;
			this.grid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
			this.colAvatar,
			lnkFullName,lnkGender,lnkJoinDate,lnkEmploymentStatus,lnkDepartmentID,lnkDesignation,lnkOnLeave,lnkBasicSalary,lnkGetAllowances8,lnkGetDeductions9,lnkGetGrossPay10,lnkGetNetPay11,
			this.ColEdit,
			this.colDel});
			this.grid.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
			this.grid.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
			this.grid.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
			this.grid.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
			this.grid.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
			this.grid.CurrentTheme.BackColor = System.Drawing.Color.White;
			this.grid.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
			this.grid.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
			this.grid.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
			this.grid.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
			this.grid.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
			this.grid.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
			this.grid.CurrentTheme.Name = null;
			this.grid.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
			this.grid.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
			this.grid.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
			this.grid.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
			this.grid.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
			dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
			dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
			dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
			dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
			dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
			dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
			this.grid.DefaultCellStyle = dataGridViewCellStyle3;
			this.grid.EnableHeadersVisualStyles = false;
			this.grid.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
			this.grid.HeaderBackColor = System.Drawing.Color.DodgerBlue;
			this.grid.HeaderBgColor = System.Drawing.Color.Empty;
			this.grid.HeaderForeColor = System.Drawing.Color.White;
			this.grid.Location = new System.Drawing.Point(10, 59);
			this.grid.Name = "grid";
			this.grid.RowHeadersVisible = false;
			this.grid.RowTemplate.Height = 40;
			this.grid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.grid.Size = new System.Drawing.Size(859, 627);
			this.grid.TabIndex = 0;
			this.grid.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
			this.grid.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.grid_CellContentClick);
			this.grid.CellContentDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.grid_CellContentDoubleClick);
			this.grid.SelectionChanged += new System.EventHandler(this.grid_SelectionChanged);
			// colAvatar
			//
			this.colAvatar.DataPropertyName = "Avatar(@FullName)";
			this.colAvatar.HeaderText = "";
			this.colAvatar.ImageLayout = System.Windows.Forms.DataGridViewImageCellLayout.Zoom;
			this.colAvatar.Name = "colAvatar";
            this.colAvatar.FillWeight = 30F;
			
                                    //
                                    // lnkFullName
                                    //
                                    this.lnkFullName.HeaderText = "Full Name";
                                    this.lnkFullName.Name = "lnkFullName";
                                    this.lnkFullName.DataPropertyName = "FullName";
                                    this.lnkFullName.ReadOnly = false;
                                    
                                    //
                                    // lnkGender
                                    //
                                    this.lnkGender.HeaderText = "Gender";
                                    this.lnkGender.Name = "lnkGender";
                                    this.lnkGender.DataPropertyName = "Gender";
                                    this.lnkGender.ReadOnly = false;
                                    
                                    //
                                    // lnkJoinDate
                                    //
                                    this.lnkJoinDate.HeaderText = "Join Date";
                                    this.lnkJoinDate.Name = "lnkJoinDate";
                                    this.lnkJoinDate.DataPropertyName = "JoinDate";
                                    this.lnkJoinDate.ReadOnly = false;
                                    
                                    //
                                    // cmbFilterEmploymentStatus
                                    //
                                    this.cmbFilterEmploymentStatus.BackColor = System.Drawing.Color.Transparent;
                                    this.cmbFilterEmploymentStatus.BackgroundColor = System.Drawing.Color.DodgerBlue;
                                    this.cmbFilterEmploymentStatus.BorderColor = System.Drawing.SystemColors.Control;
                                    this.cmbFilterEmploymentStatus.BorderRadius = 0;
                                    this.cmbFilterEmploymentStatus.Color = System.Drawing.SystemColors.Control;
                                    this.cmbFilterEmploymentStatus.Dock = System.Windows.Forms.DockStyle.Left;
                                    this.cmbFilterEmploymentStatus.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thick;
                                    this.cmbFilterEmploymentStatus.ForeColor = System.Drawing.Color.White;
                                    this.cmbFilterEmploymentStatus.IndicatorColor = System.Drawing.Color.White;
                                    this.cmbFilterEmploymentStatus.IndicatorThickness = 2;
                                    this.cmbFilterEmploymentStatus.Name = "cmbFilterEmploymentStatus ";
                                    this.cmbFilterEmploymentStatus.Size = new System.Drawing.Size(150, 32);
                                    this.cmbFilterEmploymentStatus.Text = "Employment Status (All)";
                                    this.cmbFilterEmploymentStatus.Items.AddRange(new object[] { "Employment Status (All)","Active","Deceased","Laid-off","Fired","Quit","Retired"   });
                                    this.pnlActions.Controls.Add(this.cmbFilterEmploymentStatus );
                                    this.cmbFilterEmploymentStatus.SelectionChangeCommitted += new System.EventHandler(this.filters_SelectionChangeCommitted);
                                    
                            //
                            //lnkEmploymentStatus
                            //
                            this.lnkEmploymentStatus.HeaderText = "Status";
                            this.lnkEmploymentStatus.DataPropertyName = "{GetStatus()}";
                            this.lnkEmploymentStatus.Name = "lnkEmploymentStatus";
                            this.lnkEmploymentStatus.FillWeight = 150F;
                                           this.lnkEmploymentStatus.DefaultCellStyle = colProgressStyle;
                            //
                            // cmbFilterDepartmentID
                            //
                            this.cmbFilterDepartmentID.BackColor = System.Drawing.Color.Transparent;
                            this.cmbFilterDepartmentID.BackgroundColor = System.Drawing.Color.DodgerBlue;
                            this.cmbFilterDepartmentID.BorderColor = System.Drawing.SystemColors.Control;
                            this.cmbFilterDepartmentID.BorderRadius = 0;
                            this.cmbFilterDepartmentID.Color = System.Drawing.SystemColors.Control;
                            this.cmbFilterDepartmentID.Dock = System.Windows.Forms.DockStyle.Left;
                            this.cmbFilterDepartmentID.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thick;
                            this.cmbFilterDepartmentID.ForeColor = System.Drawing.Color.White;
                            this.cmbFilterDepartmentID.IndicatorColor = System.Drawing.Color.White;
                            this.cmbFilterDepartmentID.IndicatorThickness = 2;
                            this.cmbFilterDepartmentID.Name = "cmbFilterDepartmentID ";
                            this.cmbFilterDepartmentID.Size = new System.Drawing.Size(150, 32);
                            this.cmbFilterDepartmentID.Text = "Department (All)";
                            this.cmbFilterDepartmentID.ValueMember = "DepartmentID";
                            this.cmbFilterDepartmentID.DisplayMember = "Name";
                            this.pnlActions.Controls.Add(this.cmbFilterDepartmentID );
                            this.cmbFilterDepartmentID.SelectionChangeCommitted += new System.EventHandler(this.filters_SelectionChangeCommitted);
                            
                            //
                            //lnkDepartmentID
                            //
                            this.lnkDepartmentID.HeaderText = "Department";
                            this.lnkDepartmentID.DataPropertyName = "{GetDepartmentName()}";
                            this.lnkDepartmentID.Name = "lnkDepartmentID";
                            
                                    //
                                    // lnkDesignation
                                    //
                                    this.lnkDesignation.HeaderText = "Designation";
                                    this.lnkDesignation.Name = "lnkDesignation";
                                    this.lnkDesignation.DataPropertyName = "Designation";
                                    this.lnkDesignation.ReadOnly = false;
                                    
                                    //
                                    // lnkOnLeave
                                    //
                                    this.lnkOnLeave.HeaderText = "On Leave";
                                    this.lnkOnLeave.Name = "lnkOnLeave";
                                    this.lnkOnLeave.DataPropertyName = "OnLeave";
                                    this.lnkOnLeave.ReadOnly = false;
                                    
                                    //
                                    // lnkBasicSalary
                                    //
                                    this.lnkBasicSalary.HeaderText = "Basic Salary";
                                    this.lnkBasicSalary.Name = "lnkBasicSalary";
                                    this.lnkBasicSalary.DataPropertyName = "BasicSalary";
                                    this.lnkBasicSalary.ReadOnly = false;
                                    
                            //
                            // lnkGetAllowances
                            //
                            this.lnkGetAllowances8.HeaderText = "Allowances";
                            this.lnkGetAllowances8.Name = "lnkGetAllowances8";
                            this.lnkGetAllowances8.DataPropertyName = "{GetAllowances()}";
                            this.lnkGetAllowances8.ReadOnly =true;
                            
                            //
                            // lnkGetDeductions
                            //
                            this.lnkGetDeductions9.HeaderText = "Deductions";
                            this.lnkGetDeductions9.Name = "lnkGetDeductions9";
                            this.lnkGetDeductions9.DataPropertyName = "{GetDeductions()}";
                            this.lnkGetDeductions9.ReadOnly =true;
                            
                            //
                            // lnkGetGrossPay
                            //
                            this.lnkGetGrossPay10.HeaderText = "Gross";
                            this.lnkGetGrossPay10.Name = "lnkGetGrossPay10";
                            this.lnkGetGrossPay10.DataPropertyName = "{GetGrossPay()}";
                            this.lnkGetGrossPay10.ReadOnly =true;
                            
                            //
                            // lnkGetNetPay
                            //
                            this.lnkGetNetPay11.HeaderText = "Net";
                            this.lnkGetNetPay11.Name = "lnkGetNetPay11";
                            this.lnkGetNetPay11.DataPropertyName = "{GetNetPay()}";
                            this.lnkGetNetPay11.ReadOnly =true;
                            //code
                          
                                 

			//
			// ColEdit
			//
			this.ColEdit.DataPropertyName = "✏";
			this.ColEdit.FillWeight = 30F;
			this.ColEdit.LinkBehavior = System.Windows.Forms.LinkBehavior.NeverUnderline;
			this.ColEdit.HeaderText = "";
			this.ColEdit.Name = "ColEdit";

			//
			// colDel
			//
			this.colDel.ActiveLinkColor = System.Drawing.Color.Crimson;
			this.colDel.DataPropertyName = "❌";
			this.colDel.FillWeight = 30F;
			this.colDel.HeaderText = "";
			this.colDel.LinkBehavior = System.Windows.Forms.LinkBehavior.NeverUnderline;
			this.colDel.LinkColor = System.Drawing.Color.Crimson;
			this.colDel.Name = "colDel";
			this.colDel.TrackVisitedState = false;
			this.colDel.VisitedLinkColor = System.Drawing.Color.Crimson;

			//
			// txtSearch
			//
			this.txtSearch.AcceptsReturn = false;
			this.txtSearch.AcceptsTab = false;
			this.txtSearch.AnimationSpeed = 200;
			this.txtSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.txtSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.txtSearch.AutoSizeHeight = true;
			this.txtSearch.BackColor = System.Drawing.Color.Transparent;
			this.txtSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.txtSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.txtSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.txtSearch.BorderColorIdle = System.Drawing.Color.Silver;
			this.txtSearch.BorderRadius = 1;
			this.txtSearch.BorderThickness = 1;
			this.txtSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.txtSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.txtSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.txtSearch.DefaultText = "";
			this.txtSearch.FillColor = System.Drawing.Color.White;
			this.txtSearch.HideSelection = true;
			this.txtSearch.IconLeft = null;
			this.txtSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.txtSearch.IconPadding = 10;
			this.txtSearch.IconRight = null;
			this.txtSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.txtSearch.Lines = new string[0];
			this.txtSearch.Location = new System.Drawing.Point(10, 12);
			this.txtSearch.MaxLength = 32767;
			this.txtSearch.MinimumSize = new System.Drawing.Size(1, 1);
			this.txtSearch.Modified = false;
			this.txtSearch.Multiline = false;
			this.txtSearch.Name = "txtSearch";
			stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties1.FillColor = System.Drawing.Color.Empty;
			stateProperties1.ForeColor = System.Drawing.Color.Empty;
			stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.txtSearch.OnActiveState = stateProperties1;
			stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.txtSearch.OnDisabledState = stateProperties2;
			stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties3.FillColor = System.Drawing.Color.Empty;
			stateProperties3.ForeColor = System.Drawing.Color.Empty;
			stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.txtSearch.OnHoverState = stateProperties3;
			stateProperties4.BorderColor = System.Drawing.Color.Silver;
			stateProperties4.FillColor = System.Drawing.Color.White;
			stateProperties4.ForeColor = System.Drawing.Color.Empty;
			stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.txtSearch.OnIdleState = stateProperties4;
			this.txtSearch.Padding = new System.Windows.Forms.Padding(3);
			this.txtSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.txtSearch.PlaceholderText = "Search...";
			this.txtSearch.ReadOnly = false;
			this.txtSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.txtSearch.SelectedText = "";
			this.txtSearch.SelectionLength = 0;
			this.txtSearch.SelectionStart = 0;
			this.txtSearch.ShortcutsEnabled = true;
			this.txtSearch.Size = new System.Drawing.Size(269, 30);
			this.txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.txtSearch.TabIndex = 2;
			this.txtSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.txtSearch.TextMarginBottom = 0;
			this.txtSearch.TextMarginLeft = 3;
			this.txtSearch.TextMarginTop = 1;
			this.txtSearch.TextPlaceholder = "Search...";
			this.txtSearch.UseSystemPasswordChar = false;
			this.txtSearch.WordWrap = true;
			this.txtSearch.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txtSearch_KeyUp);
			//
			// btnDelete
			//
			this.btnDelete.BackColor = System.Drawing.Color.Crimson;
			this.btnDelete.Dock = System.Windows.Forms.DockStyle.Right;
			this.btnDelete.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
			this.btnDelete.FlatAppearance.BorderSize = 2;
			this.btnDelete.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.btnDelete.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.btnDelete.ForeColor = System.Drawing.Color.White;
			this.btnDelete.Location = new System.Drawing.Point(261, 0);
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.Size = new System.Drawing.Size(112, 30);
			this.btnDelete.TabIndex = 16;
			this.btnDelete.Text = "DELETE";
			this.btnDelete.UseVisualStyleBackColor = false;
			this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
			//
			// btnAdd
			//
			this.btnAdd.BackColor = System.Drawing.Color.DodgerBlue;
			this.btnAdd.Dock = System.Windows.Forms.DockStyle.Right;
			this.btnAdd.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
			this.btnAdd.FlatAppearance.BorderSize = 2;
			this.btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.btnAdd.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.btnAdd.ForeColor = System.Drawing.Color.White;
			this.btnAdd.Location = new System.Drawing.Point(373, 0);
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.Size = new System.Drawing.Size(115, 30);
			this.btnAdd.TabIndex = 15;
			this.btnAdd.Text = "ADD";
			this.btnAdd.UseVisualStyleBackColor = false;
			this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
			//
			// btnReload
			//
			this.btnReload.BackColor = System.Drawing.Color.DodgerBlue;
			this.btnReload.Dock = System.Windows.Forms.DockStyle.Left;
			this.btnReload.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
			this.btnReload.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.btnReload.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
			this.btnReload.ForeColor = System.Drawing.Color.White;
			this.btnReload.Location = new System.Drawing.Point(0, 0);
			this.btnReload.Name = "btnReload";
			this.btnReload.Size = new System.Drawing.Size(42, 30);
			this.btnReload.TabIndex = 19;
			this.btnReload.Text = "↻";
			this.btnReload.UseVisualStyleBackColor = false;
			this.btnReload.Click += new System.EventHandler(this.btnReload_Click);
			//
			// pnlActions
			//
			this.pnlActions.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
			this.pnlActions.Location = new System.Drawing.Point(321, 12);
			this.pnlActions.Name = "pnlActions";
			this.pnlActions.Size = new System.Drawing.Size(548, 30);
			this.pnlActions.TabIndex = 17;
			this.pnlActions.Controls.Add(this.btnDelete);
			this.pnlActions.Controls.Add(this.btnAdd);
			this.pnlActions.Controls.Add(this.btnReload);
			//addFilter
			//
			// btnSearch
			//
			this.btnSearch.BackColor = System.Drawing.Color.DodgerBlue;
			this.btnSearch.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
			this.btnSearch.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.btnSearch.Font = new System.Drawing.Font("Segoe UI", 9.7F, System.Drawing.FontStyle.Bold);
			this.btnSearch.ForeColor = System.Drawing.Color.White;
			this.btnSearch.Location = new System.Drawing.Point(279, 12);
			this.btnSearch.Name = "btnSearch";
			this.btnSearch.Size = new System.Drawing.Size(42, 30);
			this.btnSearch.TabIndex = 18;
			this.btnSearch.Text = "🔎";
			this.btnSearch.UseVisualStyleBackColor = false;
			this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
		    // 
            // contextMenuStrip
            // 
            this.contextMenuStrip.Name = "contextMenuStrip";
            this.contextMenuStrip.Size = new System.Drawing.Size(61, 4);
            this.contextMenuStrip.Opening += new System.ComponentModel.CancelEventHandler(this.contextMenuStrip_Opening);
			//
			// UserControl
			//
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.WhiteSmoke;
			this.DoubleBuffered = true;
			this.Controls.Add(this.btnSearch);
			this.Controls.Add(this.txtSearch);
			this.Controls.Add(this.grid);
			this.Controls.Add(this.pnlActions);
			this.Name = "Page_Employee";
			this.Size = new System.Drawing.Size(885, 703);
			this.Load += new System.EventHandler(this.Page_Employee_Load);
			((System.ComponentModel.ISupportInitialize)(this.grid)).EndInit();
			this.pnlActions.ResumeLayout(false);
			this.ResumeLayout(false);

			}

			#endregion

			public Bunifu.UI.WinForms.BunifuDataGridView grid;
		    public System.Windows.Forms.ContextMenuStrip contextMenuStrip;
			public Bunifu.UI.WinForms.BunifuTextBox txtSearch;
			public System.Windows.Forms.Button btnDelete;
			public System.Windows.Forms.Button btnAdd;
			public System.Windows.Forms.Panel pnlActions; 
			public System.Windows.Forms.DataGridViewImageColumn colAvatar;
			public System.Windows.Forms.DataGridViewLinkColumn ColEdit;
			public System.Windows.Forms.DataGridViewLinkColumn colDel;
			public System.Windows.Forms.Button btnSearch;
			public System.Windows.Forms.Button btnReload;
			public System.Windows.Forms.DataGridViewTextBoxColumn lnkFullName;
public System.Windows.Forms.DataGridViewTextBoxColumn lnkGender;
public System.Windows.Forms.DataGridViewTextBoxColumn lnkJoinDate;
 public Bunifu.UI.WinForms.BunifuDropdown cmbFilterEmploymentStatus;public System.Windows.Forms.DataGridViewImageColumn lnkEmploymentStatus;
 public Bunifu.UI.WinForms.BunifuDropdown cmbFilterDepartmentID;public System.Windows.Forms.DataGridViewImageColumn lnkDepartmentID;
public System.Windows.Forms.DataGridViewTextBoxColumn lnkDesignation;
public System.Windows.Forms.DataGridViewTextBoxColumn lnkOnLeave;
public System.Windows.Forms.DataGridViewTextBoxColumn lnkBasicSalary;
public System.Windows.Forms.DataGridViewTextBoxColumn lnkGetAllowances8;
public System.Windows.Forms.DataGridViewTextBoxColumn lnkGetDeductions9;
public System.Windows.Forms.DataGridViewTextBoxColumn lnkGetGrossPay10;
public System.Windows.Forms.DataGridViewTextBoxColumn lnkGetNetPay11;
//declare
			}
			}