//Code Generated by Jenga.NET
using Kimtoo.BindingProvider;
using ServiceStack.OrmLite;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Windows.Forms;
namespace Payroll_Management_System.Pages
{
    public partial class Page_Department : UserControl
    {

        public bool AllowAdd { get; set; } = true;
        public bool AllowDelete { get; set; } = true;
        public bool AllowEdit { get; set; } = true;
        public bool AllowSearch { get; set; } = true;
        public int DataLimit { get; set; } = 0;
        public Func<Payroll_Management_System.Models.Department, bool> BeforeDelete { get; set; } = null;
        public Dictionary<string, object> FixedValues = new Dictionary<string, object>();
        public Dictionary<string, Action<Payroll_Management_System.Models.Department>> CustomContextMenu = new Dictionary<string, Action<Payroll_Management_System.Models.Department>>();
        private Func<Payroll_Management_System.Models.Department, bool> _dataFilter = null;
        public delegate void JengaEventHandler(Payroll_Management_System.Models.Department e);
        public event JengaEventHandler SelectionChanged = null;

        public Page_Department()
        {
            InitializeComponent();

        }

        private static bool IsInDesignMode()
        => (Application.ExecutablePath.IndexOf("devenv.exe", StringComparison.OrdinalIgnoreCase) > -1);

        public void LoadData()
        {
            Cursor.Current = Cursors.WaitCursor;
            //load Custom ContextMenu
            if (contextMenuStrip.Items.Count == 0)
                foreach (var menu in this.CustomContextMenu)
                    contextMenuStrip.Items.Add(menu.Key, null, (s, ee) => menu.Value.Invoke(grid.GetRecord<Payroll_Management_System.Models.Department>()));

            var data = Kt.Db.Select<Payroll_Management_System.Models.Department>();
            //filter
            if (_dataFilter != null)
                data = data.Where(r => _dataFilter.Invoke(r)).ToList();

            if (DataLimit > 0)
                data = data.Take(DataLimit).ToList();
            grid.Bind(data);
            Cursor.Current = Cursors.Default;
        }
        private void grid_SelectionChanged(object sender, EventArgs e)
        {
            SelectionChanged?.Invoke(grid.GetRecord<Payroll_Management_System.Models.Department>());
        }
        public Payroll_Management_System.Models.Department GetSelectedRecord()
        {
            return grid.GetRecord<Payroll_Management_System.Models.Department>();
        }
        public IEnumerable<Payroll_Management_System.Models.Department> GetCurrentRecords()
        {
            return grid.GetRecords<Payroll_Management_System.Models.Department>();
        }
        public void SetDataFilter(Func<Payroll_Management_System.Models.Department, bool> predicate)
        {
            _dataFilter = predicate;
            LoadData();
        }

        public void ClearDataFilter()
        {
            _dataFilter = null;
            LoadData();
        }

        private void LoadFilters()
        {
            Cursor.Current = Cursors.WaitCursor;
            txtSearch.Text = "";
            var db = Kt.Db;
            //fetch-filter
            Cursor.Current = Cursors.Default;
        }
        private void Page_Department_Load(object sender, EventArgs e)
        {
            ColEdit.Visible = this.AllowEdit;
            btnAdd.Visible = this.AllowAdd;
            txtSearch.Visible = btnSearch.Visible = this.AllowSearch;
            grid.AllowUserToDeleteRows = colDel.Visible = btnDelete.Visible = this.AllowDelete;
            //disable rendering on design time
            if (IsInDesignMode()) return;
            LoadFilters();

            //-Add code for deletion using Binding Provider 
            if (this.AllowDelete)
                grid.OnDelete<Payroll_Management_System.Models.Department>((r, i) => Kt.Db.Delete(r) > 0);
            //init
            LoadData();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            var frm = new Payroll_Management_System.Forms.Frm_Department();
            frm.FixedValues = this.FixedValues;
            frm.ShowDialog();
            LoadData();
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                if (BeforeDelete != null)
                    if (!BeforeDelete.Invoke(GetSelectedRecord()))
                        return;
                grid.DeleteRow<Payroll_Management_System.Models.Department>();
            }
            catch (Exception)
            {
            }
        }

        private void txtSearch_KeyUp(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                if (txtSearch.Text.Trim().Length > 0)
                    grid.SearchRows(txtSearch.Text);
                else
                    LoadData();
            }
        }
        private void btnSearch_Click(object sender, EventArgs e)
        {
            if (txtSearch.Text.Trim().Length > 0)
                grid.SearchRows(txtSearch.Text);
            else
                LoadData();
        }
        private void filters_SelectionChangeCommitted(object sender, EventArgs e)
        {
            txtSearch.Reset();
            LoadData();
        }
        private void grid_CellContentDoubleClick(object sender, DataGridViewCellEventArgs e)
        {
            //frmLink
        }

        private void btnReload_Click(object sender, EventArgs e)
        {
            LoadFilters();
            LoadData();
        }
        private void contextMenuStrip_Opening(object sender, CancelEventArgs e)
        => e.Cancel = !(grid.SelectedRows.Count > 0 && CustomContextMenu.Count() > 0);
        private void grid_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.ColumnIndex == ColEdit.Index)
            {

                var frm = new Payroll_Management_System.Forms.Frm_Department(grid.GetRecord<Payroll_Management_System.Models.Department>());
                frm.FixedValues = this.FixedValues;
                frm.ShowDialog();
                LoadData();
            }

            if (e.ColumnIndex == colDel.Index)
                grid.DeleteRow<Payroll_Management_System.Models.Department>();
        }

    }
}