//Code Generated by Jenga.NET
			namespace Payroll_Management_System.Forms
			{
			partial class Frm_Company
			{

			private System.ComponentModel.IContainer components = null;

			protected override void Dispose(bool disposing)
			{
			if (disposing && (components != null))
			{
			components.Dispose();
			}
			base.Dispose(disposing);
			}

			#region Windows Form Designer generated code

			private void InitializeComponent()
			{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Frm_Company));
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject1 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption1 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject1 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption16 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject16 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject16 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject2 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption2 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject2 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject3 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption3 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject3 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject4 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption4 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject4 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject5 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption5 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject5 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject6 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption6 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject6 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject7 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption7 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject7 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject8 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption8 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject8 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject9 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption9 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject9 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject10 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption10 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject10 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject11 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption11 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject11 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject12 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption12 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject12 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject13 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption13 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject13 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject14 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption14 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject14 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject15 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption15 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject15 = new Kimtoo.ValidationProvider.ValidationObject();
            this.Alert = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.validationProvider = new Kimtoo.ValidationProvider.ValidationProvider();
            this.AppBar = new Bunifu.Utils.BunifuAppBar();
            this.pnlContent = new System.Windows.Forms.Panel();
            this.lblCompanyName = new System.Windows.Forms.Label();
            this.txtCompanyName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblLogo = new System.Windows.Forms.Label();
            this.picLogo = new System.Windows.Forms.PictureBox();
            this.btnBrowseLogo = new System.Windows.Forms.LinkLabel();
            this.lblPhone = new System.Windows.Forms.Label();
            this.txtPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblEmail = new System.Windows.Forms.Label();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblAddress = new System.Windows.Forms.Label();
            this.txtAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblBottom = new System.Windows.Forms.Label();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnAdd = new System.Windows.Forms.Button();
            this.bindingProvider = new Kimtoo.BindingProvider.BindingProvider();
            this.themeProvider = new Kimtoo.ThemeProvider.ThemeProvider();
            this.bunifuFormDock = new Bunifu.UI.WinForms.BunifuFormDock();
            this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.pnlContent.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picLogo)).BeginInit();
            this.SuspendLayout();
            // 
            // Alert
            // 
            this.Alert.AllowDragging = false;
            this.Alert.AllowMultipleViews = true;
            this.Alert.ClickToClose = true;
            this.Alert.DoubleClickToClose = true;
            this.Alert.DurationAfterIdle = 3000;
            this.Alert.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.ErrorOptions.ActionBorderRadius = 1;
            this.Alert.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.Alert.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.Alert.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.Alert.ErrorOptions.IconLeftMargin = 12;
            this.Alert.FadeCloseIcon = false;
            this.Alert.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.Alert.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.InformationOptions.ActionBorderRadius = 1;
            this.Alert.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.InformationOptions.BackColor = System.Drawing.Color.White;
            this.Alert.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.Alert.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.Alert.InformationOptions.IconLeftMargin = 12;
            this.Alert.Margin = 10;
            this.Alert.MaximumSize = new System.Drawing.Size(0, 0);
            this.Alert.MaximumViews = 7;
            this.Alert.MessageRightMargin = 15;
            this.Alert.MinimumSize = new System.Drawing.Size(0, 0);
            this.Alert.ShowBorders = false;
            this.Alert.ShowCloseIcon = false;
            this.Alert.ShowIcon = true;
            this.Alert.ShowShadows = true;
            this.Alert.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.SuccessOptions.ActionBorderRadius = 1;
            this.Alert.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.Alert.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.Alert.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.Alert.SuccessOptions.IconLeftMargin = 12;
            this.Alert.ViewsMargin = 7;
            this.Alert.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.WarningOptions.ActionBorderRadius = 1;
            this.Alert.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.WarningOptions.BackColor = System.Drawing.Color.White;
            this.Alert.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.Alert.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.Alert.WarningOptions.IconLeftMargin = 12;
            this.Alert.ZoomCloseIcon = true;
            // 
            // validationProvider
            // 
            this.validationProvider.ErrorColor = System.Drawing.Color.Crimson;
            // 
            // AppBar
            // 
            this.AppBar.BackColor = System.Drawing.Color.DodgerBlue;
            this.AppBar.ControlBoxColor = System.Drawing.Color.WhiteSmoke;
            this.AppBar.ControlBoxColorActive = System.Drawing.Color.White;
            this.AppBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.AppBar.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.AppBar.ForeColor = System.Drawing.Color.White;
            this.AppBar.Icon = ((System.Drawing.Image)(resources.GetObject("AppBar.Icon")));
            bindingObject1.Data = "";
            bindingObject1.Property = "Text";
            bindingObject1.TwoWay = true;
            this.bindingProvider.SetLink(this.AppBar, bindingObject1);
            themeOption1.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.AppBar, themeOption1);
            validationObject1.CustomErrorMessage = "";
            validationObject1.Optional = false;
            validationObject1.PropertyName = "Text";
            validationObject1.Regex = null;
            validationObject1.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.AppBar, validationObject1);
            this.AppBar.Location = new System.Drawing.Point(0, 0);
            this.AppBar.Name = "AppBar";
            this.AppBar.Size = new System.Drawing.Size(682, 46);
            this.AppBar.TabIndex = 6;
            this.AppBar.Title = "Empresa";
            this.AppBar.TitleMargin = new System.Windows.Forms.Padding(47, 12, 0, 0);
            // 
            // pnlContent
            // 
            this.pnlContent.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlContent.AutoScroll = true;
            this.pnlContent.Controls.Add(this.lblCompanyName);
            this.pnlContent.Controls.Add(this.txtCompanyName);
            this.pnlContent.Controls.Add(this.lblLogo);
            this.pnlContent.Controls.Add(this.picLogo);
            this.pnlContent.Controls.Add(this.btnBrowseLogo);
            this.pnlContent.Controls.Add(this.lblPhone);
            this.pnlContent.Controls.Add(this.txtPhone);
            this.pnlContent.Controls.Add(this.lblEmail);
            this.pnlContent.Controls.Add(this.txtEmail);
            this.pnlContent.Controls.Add(this.lblAddress);
            this.pnlContent.Controls.Add(this.txtAddress);
            this.pnlContent.Controls.Add(this.lblBottom);
            this.pnlContent.Controls.Add(this.btnCancel);
            this.pnlContent.Controls.Add(this.btnAdd);
            themeOption16.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.pnlContent, themeOption16);
            validationObject16.CustomErrorMessage = "";
            validationObject16.Optional = false;
            validationObject16.PropertyName = "Text";
            validationObject16.Regex = null;
            validationObject16.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.pnlContent, validationObject16);
            bindingObject16.Data = "";
            bindingObject16.Property = "Text";
            bindingObject16.TwoWay = true;
            this.bindingProvider.SetLink(this.pnlContent, bindingObject16);
            this.pnlContent.Location = new System.Drawing.Point(3, 51);
            this.pnlContent.Name = "pnlContent";
            this.pnlContent.Size = new System.Drawing.Size(727, 695);
            this.pnlContent.TabIndex = 7;
            // 
            // lblCompanyName
            // 
            this.lblCompanyName.AutoSize = true;
            bindingObject2.Data = "";
            bindingObject2.Property = "Text";
            bindingObject2.TwoWay = true;
            this.bindingProvider.SetLink(this.lblCompanyName, bindingObject2);
            themeOption2.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblCompanyName, themeOption2);
            validationObject2.CustomErrorMessage = "";
            validationObject2.Optional = false;
            validationObject2.PropertyName = "Text";
            validationObject2.Regex = null;
            validationObject2.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblCompanyName, validationObject2);
            this.lblCompanyName.Location = new System.Drawing.Point(25, 30);
            this.lblCompanyName.Name = "lblCompanyName";
            this.lblCompanyName.Size = new System.Drawing.Size(181, 20);
            this.lblCompanyName.TabIndex = 0;
            this.lblCompanyName.Text = "Nombre de la compania*";
            // 
            // txtCompanyName
            // 
            this.txtCompanyName.AcceptsReturn = false;
            this.txtCompanyName.AcceptsTab = false;
            this.txtCompanyName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtCompanyName.AnimationSpeed = 200;
            this.txtCompanyName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCompanyName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCompanyName.AutoSizeHeight = true;
            this.txtCompanyName.BackColor = System.Drawing.Color.White;
            this.txtCompanyName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCompanyName.BackgroundImage")));
            this.txtCompanyName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCompanyName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCompanyName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCompanyName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCompanyName.BorderRadius = 1;
            this.txtCompanyName.BorderThickness = 1;
            this.txtCompanyName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCompanyName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCompanyName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCompanyName.DefaultText = "";
            this.txtCompanyName.FillColor = System.Drawing.Color.White;
            this.txtCompanyName.HideSelection = true;
            this.txtCompanyName.IconLeft = null;
            this.txtCompanyName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCompanyName.IconPadding = 10;
            this.txtCompanyName.IconRight = null;
            this.txtCompanyName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCompanyName.Lines = new string[0];
            bindingObject3.Data = "CompanyName";
            bindingObject3.Property = "Text";
            bindingObject3.TwoWay = true;
            this.bindingProvider.SetLink(this.txtCompanyName, bindingObject3);
            themeOption3.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.txtCompanyName, themeOption3);
            validationObject3.CustomErrorMessage = "";
            validationObject3.Optional = false;
            validationObject3.PropertyName = "Text";
            validationObject3.Regex = "(.|\\s)*\\S(.|\\s)*";
            validationObject3.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.txtCompanyName, validationObject3);
            this.txtCompanyName.Location = new System.Drawing.Point(212, 19);
            this.txtCompanyName.MaxLength = 32767;
            this.txtCompanyName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCompanyName.Modified = false;
            this.txtCompanyName.Multiline = false;
            this.txtCompanyName.Name = "txtCompanyName";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCompanyName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCompanyName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCompanyName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCompanyName.OnIdleState = stateProperties4;
            this.txtCompanyName.Padding = new System.Windows.Forms.Padding(3);
            this.txtCompanyName.PasswordChar = '\0';
            this.txtCompanyName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCompanyName.PlaceholderText = "Introduce el nombre de la compania";
            this.txtCompanyName.ReadOnly = false;
            this.txtCompanyName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCompanyName.SelectedText = "";
            this.txtCompanyName.SelectionLength = 0;
            this.txtCompanyName.SelectionStart = 0;
            this.txtCompanyName.ShortcutsEnabled = true;
            this.txtCompanyName.Size = new System.Drawing.Size(443, 43);
            this.txtCompanyName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCompanyName.TabIndex = 1;
            this.txtCompanyName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCompanyName.TextMarginBottom = 0;
            this.txtCompanyName.TextMarginLeft = 3;
            this.txtCompanyName.TextMarginTop = 1;
            this.txtCompanyName.TextPlaceholder = "Introduce el nombre de la compania";
            this.txtCompanyName.UseSystemPasswordChar = false;
            this.txtCompanyName.WordWrap = true;
            // 
            // lblLogo
            // 
            this.lblLogo.AutoSize = true;
            bindingObject4.Data = "";
            bindingObject4.Property = "Text";
            bindingObject4.TwoWay = true;
            this.bindingProvider.SetLink(this.lblLogo, bindingObject4);
            themeOption4.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblLogo, themeOption4);
            validationObject4.CustomErrorMessage = "";
            validationObject4.Optional = false;
            validationObject4.PropertyName = "Text";
            validationObject4.Regex = null;
            validationObject4.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblLogo, validationObject4);
            this.lblLogo.Location = new System.Drawing.Point(25, 100);
            this.lblLogo.Name = "lblLogo";
            this.lblLogo.Size = new System.Drawing.Size(43, 20);
            this.lblLogo.TabIndex = 2;
            this.lblLogo.Text = "Logo";
            // 
            // picLogo
            // 
            this.picLogo.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            bindingObject5.Data = "";
            bindingObject5.Property = "Text";
            bindingObject5.TwoWay = true;
            this.bindingProvider.SetLink(this.picLogo, bindingObject5);
            themeOption5.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.picLogo, themeOption5);
            validationObject5.CustomErrorMessage = "";
            validationObject5.Optional = false;
            validationObject5.PropertyName = "Text";
            validationObject5.Regex = null;
            validationObject5.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.picLogo, validationObject5);
            this.picLogo.Location = new System.Drawing.Point(150, 98);
            this.picLogo.Name = "picLogo";
            this.picLogo.Size = new System.Drawing.Size(150, 150);
            this.picLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picLogo.TabIndex = 3;
            this.picLogo.TabStop = false;
            // 
            // btnBrowseLogo
            // 
            this.btnBrowseLogo.AutoSize = true;
            bindingObject6.Data = "";
            bindingObject6.Property = "Text";
            bindingObject6.TwoWay = true;
            this.bindingProvider.SetLink(this.btnBrowseLogo, bindingObject6);
            themeOption6.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.btnBrowseLogo, themeOption6);
            validationObject6.CustomErrorMessage = "";
            validationObject6.Optional = false;
            validationObject6.PropertyName = "Text";
            validationObject6.Regex = null;
            validationObject6.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.btnBrowseLogo, validationObject6);
            this.btnBrowseLogo.LinkColor = System.Drawing.Color.RoyalBlue;
            this.btnBrowseLogo.Location = new System.Drawing.Point(150, 260);
            this.btnBrowseLogo.Name = "btnBrowseLogo";
            this.btnBrowseLogo.Size = new System.Drawing.Size(158, 20);
            this.btnBrowseLogo.TabIndex = 4;
            this.btnBrowseLogo.TabStop = true;
            this.btnBrowseLogo.Text = "Selecciona un archivo";
            this.btnBrowseLogo.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.btnBrowseLogo_LinkClicked);
            // 
            // lblPhone
            // 
            this.lblPhone.AutoSize = true;
            bindingObject7.Data = "";
            bindingObject7.Property = "Text";
            bindingObject7.TwoWay = true;
            this.bindingProvider.SetLink(this.lblPhone, bindingObject7);
            themeOption7.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblPhone, themeOption7);
            validationObject7.CustomErrorMessage = "";
            validationObject7.Optional = false;
            validationObject7.PropertyName = "Text";
            validationObject7.Regex = null;
            validationObject7.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblPhone, validationObject7);
            this.lblPhone.Location = new System.Drawing.Point(25, 320);
            this.lblPhone.Name = "lblPhone";
            this.lblPhone.Size = new System.Drawing.Size(75, 20);
            this.lblPhone.TabIndex = 5;
            this.lblPhone.Text = "Telefono*";
            // 
            // txtPhone
            // 
            this.txtPhone.AcceptsReturn = false;
            this.txtPhone.AcceptsTab = false;
            this.txtPhone.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtPhone.AnimationSpeed = 200;
            this.txtPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhone.AutoSizeHeight = true;
            this.txtPhone.BackColor = System.Drawing.Color.White;
            this.txtPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhone.BackgroundImage")));
            this.txtPhone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPhone.BorderRadius = 1;
            this.txtPhone.BorderThickness = 1;
            this.txtPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPhone.DefaultText = "";
            this.txtPhone.FillColor = System.Drawing.Color.White;
            this.txtPhone.HideSelection = true;
            this.txtPhone.IconLeft = null;
            this.txtPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.IconPadding = 10;
            this.txtPhone.IconRight = null;
            this.txtPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.Lines = new string[0];
            bindingObject8.Data = "Phone";
            bindingObject8.Property = "Text";
            bindingObject8.TwoWay = true;
            this.bindingProvider.SetLink(this.txtPhone, bindingObject8);
            themeOption8.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.txtPhone, themeOption8);
            validationObject8.CustomErrorMessage = "";
            validationObject8.Optional = false;
            validationObject8.PropertyName = "Text";
            validationObject8.Regex = "^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$";
            validationObject8.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.txtPhone, validationObject8);
            this.txtPhone.Location = new System.Drawing.Point(150, 310);
            this.txtPhone.MaxLength = 32767;
            this.txtPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhone.Modified = false;
            this.txtPhone.Multiline = false;
            this.txtPhone.Name = "txtPhone";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhone.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnIdleState = stateProperties8;
            this.txtPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhone.PasswordChar = '\0';
            this.txtPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhone.PlaceholderText = "Introduce un numero de telefono";
            this.txtPhone.ReadOnly = false;
            this.txtPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhone.SelectedText = "";
            this.txtPhone.SelectionLength = 0;
            this.txtPhone.SelectionStart = 0;
            this.txtPhone.ShortcutsEnabled = true;
            this.txtPhone.Size = new System.Drawing.Size(463, 43);
            this.txtPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhone.TabIndex = 6;
            this.txtPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhone.TextMarginBottom = 0;
            this.txtPhone.TextMarginLeft = 3;
            this.txtPhone.TextMarginTop = 1;
            this.txtPhone.TextPlaceholder = "Introduce un numero de telefono";
            this.txtPhone.UseSystemPasswordChar = false;
            this.txtPhone.WordWrap = true;
            // 
            // lblEmail
            // 
            this.lblEmail.AutoSize = true;
            bindingObject9.Data = "";
            bindingObject9.Property = "Text";
            bindingObject9.TwoWay = true;
            this.bindingProvider.SetLink(this.lblEmail, bindingObject9);
            themeOption9.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblEmail, themeOption9);
            validationObject9.CustomErrorMessage = "";
            validationObject9.Optional = false;
            validationObject9.PropertyName = "Text";
            validationObject9.Regex = null;
            validationObject9.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblEmail, validationObject9);
            this.lblEmail.Location = new System.Drawing.Point(25, 390);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.Size = new System.Drawing.Size(53, 20);
            this.lblEmail.TabIndex = 7;
            this.lblEmail.Text = "Email*";
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.AutoSizeHeight = true;
            this.txtEmail.BackColor = System.Drawing.Color.White;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            bindingObject10.Data = "Email";
            bindingObject10.Property = "Text";
            bindingObject10.TwoWay = true;
            this.bindingProvider.SetLink(this.txtEmail, bindingObject10);
            themeOption10.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.txtEmail, themeOption10);
            validationObject10.CustomErrorMessage = "";
            validationObject10.Optional = false;
            validationObject10.PropertyName = "Text";
            validationObject10.Regex = resources.GetString("validationObject10.Regex");
            validationObject10.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.txtEmail, validationObject10);
            this.txtEmail.Location = new System.Drawing.Point(150, 380);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties12;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "Introduce un correo electronico";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(463, 43);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 8;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 1;
            this.txtEmail.TextPlaceholder = "Introduce un correo electronico";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // lblAddress
            // 
            this.lblAddress.AutoSize = true;
            bindingObject11.Data = "";
            bindingObject11.Property = "Text";
            bindingObject11.TwoWay = true;
            this.bindingProvider.SetLink(this.lblAddress, bindingObject11);
            themeOption11.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblAddress, themeOption11);
            validationObject11.CustomErrorMessage = "";
            validationObject11.Optional = false;
            validationObject11.PropertyName = "Text";
            validationObject11.Regex = null;
            validationObject11.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblAddress, validationObject11);
            this.lblAddress.Location = new System.Drawing.Point(25, 460);
            this.lblAddress.Name = "lblAddress";
            this.lblAddress.Size = new System.Drawing.Size(74, 20);
            this.lblAddress.TabIndex = 9;
            this.lblAddress.Text = "Direccion";
            // 
            // txtAddress
            // 
            this.txtAddress.AcceptsReturn = false;
            this.txtAddress.AcceptsTab = false;
            this.txtAddress.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtAddress.AnimationSpeed = 200;
            this.txtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddress.AutoSizeHeight = true;
            this.txtAddress.BackColor = System.Drawing.Color.White;
            this.txtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddress.BackgroundImage")));
            this.txtAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAddress.BorderRadius = 1;
            this.txtAddress.BorderThickness = 1;
            this.txtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAddress.DefaultText = "";
            this.txtAddress.FillColor = System.Drawing.Color.White;
            this.txtAddress.HideSelection = true;
            this.txtAddress.IconLeft = null;
            this.txtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.IconPadding = 10;
            this.txtAddress.IconRight = null;
            this.txtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.Lines = new string[0];
            bindingObject12.Data = "Address";
            bindingObject12.Property = "Text";
            bindingObject12.TwoWay = true;
            this.bindingProvider.SetLink(this.txtAddress, bindingObject12);
            themeOption12.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.txtAddress, themeOption12);
            validationObject12.CustomErrorMessage = "";
            validationObject12.Optional = true;
            validationObject12.PropertyName = "Text";
            validationObject12.Regex = "";
            validationObject12.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.txtAddress, validationObject12);
            this.txtAddress.Location = new System.Drawing.Point(150, 450);
            this.txtAddress.MaxLength = 32767;
            this.txtAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAddress.Modified = false;
            this.txtAddress.Multiline = true;
            this.txtAddress.Name = "txtAddress";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddress.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnIdleState = stateProperties16;
            this.txtAddress.Padding = new System.Windows.Forms.Padding(3);
            this.txtAddress.PasswordChar = '\0';
            this.txtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddress.PlaceholderText = "Introduce una direccion";
            this.txtAddress.ReadOnly = false;
            this.txtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddress.SelectedText = "";
            this.txtAddress.SelectionLength = 0;
            this.txtAddress.SelectionStart = 0;
            this.txtAddress.ShortcutsEnabled = true;
            this.txtAddress.Size = new System.Drawing.Size(463, 130);
            this.txtAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAddress.TabIndex = 10;
            this.txtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddress.TextMarginBottom = 0;
            this.txtAddress.TextMarginLeft = 3;
            this.txtAddress.TextMarginTop = 1;
            this.txtAddress.TextPlaceholder = "Introduce una direccion";
            this.txtAddress.UseSystemPasswordChar = false;
            this.txtAddress.WordWrap = true;
            // 
            // lblBottom
            // 
            this.lblBottom.AutoSize = true;
            bindingObject13.Data = "";
            bindingObject13.Property = "Text";
            bindingObject13.TwoWay = true;
            this.bindingProvider.SetLink(this.lblBottom, bindingObject13);
            themeOption13.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblBottom, themeOption13);
            validationObject13.CustomErrorMessage = "";
            validationObject13.Optional = false;
            validationObject13.PropertyName = "Text";
            validationObject13.Regex = null;
            validationObject13.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblBottom, validationObject13);
            this.lblBottom.Location = new System.Drawing.Point(25, 680);
            this.lblBottom.Name = "lblBottom";
            this.lblBottom.Size = new System.Drawing.Size(0, 20);
            this.lblBottom.TabIndex = 11;
            // 
            // btnCancel
            // 
            this.btnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancel.FlatAppearance.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCancel.FlatAppearance.BorderSize = 2;
            this.btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.DodgerBlue;
            bindingObject14.Data = "";
            bindingObject14.Property = "Text";
            bindingObject14.TwoWay = true;
            this.bindingProvider.SetLink(this.btnCancel, bindingObject14);
            themeOption14.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.btnCancel, themeOption14);
            validationObject14.CustomErrorMessage = "";
            validationObject14.Optional = false;
            validationObject14.PropertyName = "Text";
            validationObject14.Regex = null;
            validationObject14.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.btnCancel, validationObject14);
            this.btnCancel.Location = new System.Drawing.Point(389, 630);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(94, 40);
            this.btnCancel.TabIndex = 13;
            this.btnCancel.Text = "Cancelar";
            this.btnCancel.UseVisualStyleBackColor = false;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnAdd
            // 
            this.btnAdd.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAdd.BackColor = System.Drawing.Color.DodgerBlue;
            this.btnAdd.FlatAppearance.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAdd.FlatAppearance.BorderSize = 2;
            this.btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdd.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAdd.ForeColor = System.Drawing.Color.White;
            bindingObject15.Data = "";
            bindingObject15.Property = "Text";
            bindingObject15.TwoWay = true;
            this.bindingProvider.SetLink(this.btnAdd, bindingObject15);
            themeOption15.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.btnAdd, themeOption15);
            validationObject15.CustomErrorMessage = "";
            validationObject15.Optional = false;
            validationObject15.PropertyName = "Text";
            validationObject15.Regex = null;
            validationObject15.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.btnAdd, validationObject15);
            this.btnAdd.Location = new System.Drawing.Point(507, 630);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new System.Drawing.Size(115, 40);
            this.btnAdd.TabIndex = 12;
            this.btnAdd.Text = "Guardar";
            this.btnAdd.UseVisualStyleBackColor = false;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // bunifuFormDock
            // 
            this.bunifuFormDock.AllowFormDragging = true;
            this.bunifuFormDock.AllowFormDropShadow = true;
            this.bunifuFormDock.AllowFormResizing = true;
            this.bunifuFormDock.AllowHidingBottomRegion = true;
            this.bunifuFormDock.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock.ContainerControl = this;
            this.bunifuFormDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock.DockingOptions.DockAll = true;
            this.bunifuFormDock.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock.DockingOptions.DockLeft = true;
            this.bunifuFormDock.DockingOptions.DockRight = true;
            this.bunifuFormDock.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock.DockingOptions.DockTopRight = true;
            this.bunifuFormDock.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock.ParentForm = this;
            this.bunifuFormDock.ShowCursorChanges = true;
            this.bunifuFormDock.ShowDockingIndicators = false;
            this.bunifuFormDock.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock.TitleBarOptions.BunifuFormDock = this.bunifuFormDock;
            this.bunifuFormDock.TitleBarOptions.DoubleClickToExpandWindow = false;
            this.bunifuFormDock.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // openFileDialog
            // 
            this.openFileDialog.FileName = "openFileDialog";
            // 
            // Frm_Company
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ClientSize = new System.Drawing.Size(682, 753);
            this.Controls.Add(this.pnlContent);
            this.Controls.Add(this.AppBar);
            this.DoubleBuffered = true;
            this.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximizeBox = false;
            this.Name = "Frm_Company";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Frm_Company";
            this.Load += new System.EventHandler(this.Frm_Load);
            this.pnlContent.ResumeLayout(false);
            this.pnlContent.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picLogo)).EndInit();
            this.ResumeLayout(false);

			}

			#endregion
			public Kimtoo.ValidationProvider.ValidationProvider validationProvider;
			public Kimtoo.BindingProvider.BindingProvider bindingProvider;
		    public Kimtoo.ThemeProvider.ThemeProvider themeProvider;
			public System.Windows.Forms.Button btnAdd;
			public System.Windows.Forms.Button btnCancel;
			public Bunifu.Utils.BunifuAppBar AppBar;
			public System.Windows.Forms.Panel pnlContent;
			public Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock;
			public Bunifu.UI.WinForms.BunifuSnackbar Alert;
		    public System.Windows.Forms.OpenFileDialog openFileDialog;
			public System.Windows.Forms.Label lblCompanyName;
public Bunifu.UI.WinForms.BunifuTextBox txtCompanyName;
public System.Windows.Forms.Label lblLogo;
private System.Windows.Forms.PictureBox picLogo;
System.Windows.Forms.LinkLabel btnBrowseLogo;
public System.Windows.Forms.Label lblPhone;
public Bunifu.UI.WinForms.BunifuTextBox txtPhone;
public System.Windows.Forms.Label lblEmail;
public Bunifu.UI.WinForms.BunifuTextBox txtEmail;
public System.Windows.Forms.Label lblAddress;
public Bunifu.UI.WinForms.BunifuTextBox txtAddress;
public System.Windows.Forms.Label lblBottom;
//declare
			}
			}